name = "hypr"

bashrc = [
    "if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then",
    "    exec start-hyprland",
    "fi",
]

[packages]
pacman = [
    "hyprland",
    "hyprlock",
    "hyprpaper",
    "wl-clipboard",
    "waybar",
    "xdg-desktop-portal-hyprland",
]
aur = ["hyprshot"]
