name = "arch"

bashrc = [
    "export CONFIG_REPO=git@github.com:KaiPenazzi/configs.git",
    "alias vi='nvim .'",
    "export PATH=\"$HOME/.cargo/bin:$PATH\"",
]

[packages]
pacman = [
    "htop",
    "keepassxc",
    "unzip",
    "webkit2gtk",
    "zip",
    "fastfetch",
    "chafa",
]

aur = ["aura", "spotify", "insomnia", "zen-browser-bin"]
