name = "arch"

bashrc = [
    "export CONFIG_REPO=git@github.com:KaiPenazzi/configs.git",
    "alias vi='nvim .'",
    "export PATH=\"$HOME/.cargo/bin:$PATH\"",
]

[packages]
pacman = [
    "bluetoothctl",
    "bluez",
    "bluez-utils",
    "chafa",
    "fastfetch",
    "htop",
    "keepassxc",
    "pipewire",
    "pipewire-alsa",
    "pipewire-pulse",
    "tlp",
    "tlp-rdw",
    "unzip",
    "webkit2gtk",
    "zip",
    "git",
]

aur = ["aura", "spotify", "insomnia", "zen-browser-bin"]
