name = "arch"

bashrc = [
    "export CONFIG_REPO=git@github.com:KaiPenazzi/configs.git",
    "alias vi='nvim .'",
    "export PATH=\"$HOME/.cargo/bin:$PATH\"",
]

[packages]
pacman = [
    "discord",
    "firefox",
    "htop",
    "keepassxc",
    "nextcloud-client",
    "unzip",
    "webkit2gtk",
    "zip",
    "fastfetch",
    "chafa",
    "qmk",
    "borgbackup",
]

aur = [
    "aura",
    "spotify",
    "texlive-installer",
    "atlauncher",
    "insomnia",
    "zen-browser-bin",
]
